name: auto-merge

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
