name: "Lint"

on:
  push:
  pull_request:
  
permissions:
  contents: write

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871" # v4.2.1

        - name: "Set up Python"
          uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
          with:
            python-version: "3.12.4"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Format"
          run: python3 -m ruff format .
          
        - name: "Check"
          run: python3 -m ruff check . --fix
          
        - name: "Auto Commit"
          uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
          with:
            commit_message: 'style fixes by ruff'