name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has been no activity in this issue for some time. This issue is being closed but feel free to re-open the issue if needed.'
        stale-pr-message: 'There has been no activity in this pull request for some time. This pull request is being closed but feel free to re-open the pull request if needed.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
