name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        exempt-issue-assignees: 'cloneofghosts'
        exempt-pr-assignees: 'cloneofghosts'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale since it has had no activity for the last 90 days. To prevent it from being closed please comment within the next 7 days.'
        stale-pr-message: 'This pull request has been marked as stale since it has had no activity for the last 90 days. To prevent it from being closed please comment within the next 7 days.'
        close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
        close-pr-message: 'This pull request was closed because it has been stalled for 7 days with no activity.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 90
        days-before-close: 7
        enable-statistics: 'true'
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.0.1
        with:
          issue-inactive-days: '30'
          pr-inactive-days: '30'
          issue-lock-reason: ''
